select EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
from Employees join DEPARTMENTS using (DEPARTMENT_ID);

select distinct CITY, DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
from DEPARTMENTS join LOCATIONS using (LOCATION_ID) group by CITY, DEPARTMENT_NAME, LOCATION_ID, DEPARTMENT_ID;